import { readFile, writeFile } from 'node:fs/promises';

// Generate self-contained snippets: the Runtime does not support imports.
const directory = new URL('./', import.meta.url);
const common = await readFile(new URL('src/common.js', directory), 'utf8');
for (const stage of ['request', 'response']) {
  const source = await readFile(new URL(`src/${stage}.js`, directory), 'utf8');
  const result = `// Generated by build.mjs. Edit src/ and regenerate.\n${common}\n${source}`;
  const destination = new URL(`${stage}.js`, directory);
  if (process.argv.includes('--check')) {
    if (await readFile(destination, 'utf8') !== result) {
      throw new Error(`${stage}.js is out of date; run node javascript/hide-local-identity/build.mjs`);
    }
  } else {
    await writeFile(destination, result);
  }
}
