Map<String, Object?> runtimeUsagePayload() => {
  'schema': 'vibermate-runtime-usage-report-v1',
  'generatedAt': '2026-08-24T14:00:00.000Z',
  'truncated': false,
  'users': [
    {
      'userId': 'user.test',
      'username': 'alice',
      'state': 'active',
      'captureRuns': 1,
      'activeRuns': 0,
      'turns': 2,
      'succeeded': 1,
      'failed': 1,
      'canceled': 0,
      'contentUnavailableTurns': 0,
      'modelUnavailableTurns': 0,
      'tokens': tokenUsagePayload(),
      'latestContext': {
        'loginSessionId': 'login.test',
        'deviceName': 'MacBook Pro',
        'machineId': 'machine.test',
        'workspaceId': 'workspace.test',
        'workspaceLabel': 'vibermate',
        'observedAt': '2026-08-24T13:59:00.000Z',
      },
      'lastActivityAt': '2026-08-24T13:58:00.000Z',
      'models': [
        {
          'requestedModel': 'gpt-5.6-sol',
          'upstreamModel': 'relay:model/custom',
          'turns': 2,
          'succeeded': 1,
          'failed': 1,
          'canceled': 0,
          'tokens': tokenUsagePayload(),
        },
      ],
      'contexts': [
        {
          'loginSessionId': 'login.test',
          'deviceName': 'MacBook Pro',
          'machineId': 'machine.test',
          'workspaceId': 'workspace.test',
          'workspaceLabel': 'vibermate',
          'captureRuns': 1,
          'activeRuns': 0,
          'turns': 2,
          'succeeded': 1,
          'failed': 1,
          'canceled': 0,
          'tokens': tokenUsagePayload(),
          'lastActivityAt': '2026-08-24T13:58:00.000Z',
        },
      ],
      'agentSessions': [
        {
          'client': 'codex',
          'sessionId': 'native-session-one',
          'captureRuns': 1,
          'turns': 2,
          'succeeded': 1,
          'failed': 1,
          'canceled': 0,
          'tokens': tokenUsagePayload(),
          'lastActivityAt': '2026-08-24T13:58:00.000Z',
        },
      ],
    },
  ],
};

Map<String, Object?> tokenUsagePayload() => {
  'inputUncached': {'tokens': 42, 'knownTurns': 1, 'unknownTurns': 1},
  'cacheWrite': {'tokens': 0, 'knownTurns': 0, 'unknownTurns': 2},
  'cacheRead': {'tokens': 5, 'knownTurns': 1, 'unknownTurns': 1},
  'output': {'tokens': 9, 'knownTurns': 1, 'unknownTurns': 1},
  'reasoning': {'tokens': 0, 'knownTurns': 0, 'unknownTurns': 2},
};
